Add facility to sync functions
NSLS2/nsls2api pull request #126
Opened 2024-12-20 21:59 UTC by stuartcampbell

Exposed the facility name to various functions and endpoints.   

I have not extensively tested this yet.

2024-12-23 03:41 UTC, JunAishima commented
I've tried pushing a commit to your branch but could not do so.

Here is the diff:

```
diff --git a/src/nsls2api/api/v1/facility_api.py b/src/nsls2api/api/v1/facility_api.py
index 89002d0..4bd2f02 100644
--- a/src/nsls2api/api/v1/facility_api.py
+++ b/src/nsls2api/api/v1/facility_api.py
@@ -69,7 +69,7 @@ async def get_proposals_for_cycle(facility: FacilityName, cycle: str):
             status_code=501,
         )
 
-    proposal_list = await proposal_service.fetch_proposals_for_cycle(cycle)
+    proposal_list = await proposal_service.fetch_proposals_for_cycle(cycle, facility)
     if proposal_list is None:
         return fastapi.responses.JSONResponse(
             {"error": f"No proposals were found for cycle {cycle}"},
```

2024-12-23 03:42 UTC, JunAishima commented
Also looks like the stats need to be updated - currently only handling nsls2.

2024-12-31 16:49 UTC, JunAishima reviewed
please clarify how the facility name is going to be set in sync_proposals_for_cycle - will it be added to the URL, or will it need to be part of the request? or will another method be required?

2024-12-31 16:49 UTC, JunAishima commented on src/nsls2api/api/v1/jobs_api.py
> +async def sync_proposals_for_cycle(request: Request, cycle: str,
where is the best place to the facility in the URL, if that is possible? or would this be part of the request instead?

2025-01-03 13:48 UTC, JunAishima commented on src/nsls2api/api/v1/jobs_api.py
> +async def sync_proposals_for_cycle(request: Request, cycle: str,
my misunderstanding - sending in as a parameter seems better than putting the facility into the URL.

2025-01-07 22:35 UTC, nmaytan submitted a review, later dismissed

2025-01-07 22:35 UTC, nmaytan commented on src/nsls2api/services/background_service.py
> +                        f"Processing job {job.id} to synchronize proposals for the {job.sync_parameters.facility} facilities cycle {job.sync_parameters.cycle} (from {job.sync_parameters.sync_source})
This should be singular "facility" ?

2025-01-07 22:40 UTC, nmaytan commented on src/nsls2api/api/v1/jobs_api.py
> +async def sync_proposals_for_cycle(request: Request, cycle: str,
Other sync routes seem to put the facility in the URL - any reason for this not to be symmetric to that?

2025-01-07 22:44 UTC, nmaytan commented
Are proposals ID guaranteed by PASS to be unique across facilities? This obviously could impact [other things](https://github.com/NSLS2/nsls2api/blob/1a193ad96b2e23462cb5294e55a1897071b185e3/src/nsls2api/api/v1/jobs_api.py#L52) - pardon my ignorance about this detail.

2025-01-08 17:58 UTC, JunAishima commented
> Are proposals ID guaranteed by PASS to be unique across facilities? This obviously could impact [other things](https://github.com/NSLS2/nsls2api/blob/1a193ad96b2e23462cb5294e55a1897071b185e3/src/nsls2api/api/v1/jobs_api.py#L52) - pardon my ignorance about this detail.

My understanding is that the proposal IDs are a common pool so there could be proposal IDs that are the same between facilities, but only when the proposal will potentially use multiple facilities. I also asked this question before as it is not obvious from our code or the PASS API documentation.

2025-01-08 18:01 UTC, JunAishima commented
Diff to fix the issue with text when synchronizing proposals_for_cycle:

2025-01-08 19:05 UTC, JunAishima reviewed
added suggested change to background_service.py to fix awkward text

2025-01-08 19:34 UTC, nmaytan commented
> My understanding is that the proposal IDs are a common pool so there could be proposal IDs that are the same between facilities, but only when the proposal will potentially use multiple facilities. I also asked this question before as it is not obvious from our code or the PASS API documentation.

In this case, hopefully the proposal is just one singular entity in PASS? i.e. not two entities that just have the same proposal ID but may have differing "metadata" otherwise. Some partial evidence of this is that when you retrieve a proposal through nsls2api, there is no facility field (not sure if that is reflective of its state in PASS)

2025-01-09 14:53 UTC, JunAishima commented on src/nsls2api/services/background_service.py
> +                        f"Processing job {job.id} to synchronize proposals for the {job.sync_parameters.facility} facilities cycle {job.sync_parameters.cycle} (from {job.sync_parameters.sync_source})
suggestion updated with your clarified suggestion!

2025-01-09 15:00 UTC, JunAishima commented
one last suggestion to fix the check for facility name in get_proposals_for_cycle():
```
diff --git a/src/nsls2api/api/v1/facility_api.py b/src/nsls2api/api/v1/facility_api.py
index 4bd2f02..c4e066a 100644
--- a/src/nsls2api/api/v1/facility_api.py
+++ b/src/nsls2api/api/v1/facility_api.py
@@ -62,7 +62,7 @@ async def get_facility_cycles(facility: FacilityName):
     include_in_schema=True,
 )
 async def get_proposals_for_cycle(facility: FacilityName, cycle: str):
-    if facility.name != "nsls2":
+    if facility.name not in ("nsls2", "lbms"):
         # TODO: Add other facilities
         return fastapi.responses.JSONResponse(
             {"message": f"Not implemented for the {facility.name} facility."},
```

2025-01-09 15:27 UTC, stuartcampbell commented on src/nsls2api/api/v1/jobs_api.py
> +async def sync_proposals_for_cycle(request: Request, cycle: str,
It was mainly that I wasn't sure of a nice syntax that was clear .. so I added it as a query parameter.  

I could go the other way and remove the path parameters, so we would get something like ... 

```
/v1/sync/cycles/?facility=lbms
/v1/sync/cycles/?facility=nsls2
```

probably would keep a default value when no facility is specified. 

I'm happy to change the URLs for any of these sync endpoints ... I'm not tied to anything that was done already.

2025-01-09 15:28 UTC, stuartcampbell commented
> Are proposals ID guaranteed by PASS to be unique across facilities? This obviously could impact [other things](https://github.com/NSLS2/nsls2api/blob/1a193ad96b2e23462cb5294e55a1897071b185e3/src/nsls2api/api/v1/jobs_api.py#L52) - pardon my ignorance about this detail.

I've checked this in the past with the PASS developers and yes - all proposal ids are unique across all of PASS irrespective of what facility they are for.

2025-01-09 16:45 UTC, JunAishima commented on src/nsls2api/api/v1/jobs_api.py
> +async def sync_proposals_for_cycle(request: Request, cycle: str,
the one that would be a good model (though potentially confusing because they are so similar) is

`/facility/{facility}/cycle/{cycle}/proposals`

so would the following be a good change (though we would make facility mandatory)?

`/sync/facility/{facility}/cycle/{cycle}/proposals`

2025-01-09 22:02 UTC, JunAishima requested changes
one last minor spelling change!

2025-01-09 22:02 UTC, JunAishima commented on src/nsls2api/services/background_service.py
> +                        job.sync_parameters.cycle, job.sync_paramters.facility
```suggestion
                        job.sync_parameters.cycle, job.sync_parameters.facility
```

2025-01-09 22:13 UTC, stuartcampbell commented on src/nsls2api/services/background_service.py
> +                        job.sync_parameters.cycle, job.sync_paramters.facility
Good catch

2025-01-09 22:14 UTC, JunAishima approved these changes

2025-01-09 22:15 UTC, stuartcampbell commented
Self merging as changes have been approved by @JunAishima

2025-01-09 22:16 UTC, merged